export const rows = [
  {
    id: 1,
    name: "Nour Amri",
    email: "Nouramri612@gmail.com",
    age: 22,
    phone: "(665)121-5454",
    access: "Admin",
  },
  {
    id: 2,
    name: "Mark Zuckerberg",
    email: "markzuckerberg@facebook.com",
    age: 40,
    phone: "(421)314-2288",
    access: "Admin",
  },
  {
    id: 3,
    name: "Jeff Bezos",
    email: "jeffbezos@amazon.com",
    age: 59,
    phone: "(422)982-6739",
    access: "Admin",
  },
  {
    id: 4,
    name: "Larry Page",
    email: "larrypage@google.com",
    age: 50,
    phone: "(921)425-6742",
    access: "Manager",
  },
  {
    id: 5,
    name: "Sergey Brin",
    email: "sergeybrin@google.com",
    age: 50,
    phone: "(421)445-1189",
    access: "Manager",
  },
  {
    id: 6,
    name: "Elon Musk",
    email: "elonmusk@tesla.com",
    age: 52,
    phone: "(321)555-1212",
    access: "Manager",
  },
  {
    id: 7,
    name: "Bill Gates",
    email: "billgates@microsoft.com",
    age: 68,
    phone: "(123)456-7890",
    access: "Manager",
  },
  {
    id: 8,
    name: "Satya Nadella",
    email: "satyanadella@microsoft.com",
    age: 56,
    phone: "(232)545-6483",
    access: "User",
  },
  {
    id: 9,
    name: "Ada Lovelace",
    email: "adalovelace@computing.com",
    age: 36,
    phone: "(987)654-3210",
    access: "User",
  },
  {
    id: 10,
    name: "Albert Einstein",
    email: "aeinstein@theory.com",
    age: 76,
    phone: "(456)789-1234",
    access: "User",
  },
  {
    id: 11,
    name: "Marie Curie",
    email: "mariecurie@science.com",
    age: 66,
    phone: "(345)678-9012",
    access: "User",
  },
  {
    id: 12,
    name: "Olivia Nogueiira",
    email: "olivianogueiira@gmail.com",
    age: 29,
    phone: "(555)123-4567",
    access: "User",
  },
  {
    id: 13,
    name: "Liv Szczpank",
    email: "livszczpank@gmail.com",
    age: 27,
    phone: "(543)124-0123",
    access: "User",
  },
  {
    id: 14,
    name: "Maike Conrad",
    email: "maikeconrad@gmail.com",
    age: 25,
    phone: "(222)444-5555",
    access: "User",
  },
  {
    id: 15,
    name: "Lucia Garcia",
    email: "luciagarcia@gmail.com",
    age: 26,
    phone: "(444)555-6239",
    access: "User",
  },
  {
    id: 16,
    name: "Eva Fernandez",
    email: "evafernandez@gmail.com",
    age: 24,
    phone: "(555)666-7890",
    access: "User",
  },
];
